config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  get 'services' => 'pages#services', as: 'services'
  get 'contact' => 'pages#contact', as: 'contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true,
                        length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "Tonny", password: "1234", only: [:destroy]

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private
    def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
       @title = 'Welcome'
       @content = 'Welcome to the home page' 
    end

    def about
        @title = 'About'
        @content = 'Welcome to the about page'
    end

    def services
        @title = 'Services'
        @content = 'Welcome to the services page'
        @services = ['Web Development', 'Mobile Development', 'Software Engineering']
    end

    def contact
        @title = 'Contact'
        @content = 'Welcome to the contact page'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "Tonny", password: "1234", except: [:index, :show] 

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else 
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else 
      render 'edit'
    end

  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
    <div class="comments">
    <% @post.comments.each do |comment| %>
        <div class="card-body-comment">
            <p><strong><%= comment.username %>: </strong><%= comment.body %>
            <%= link_to '[X]',[comment.post, comment], method: :delete, date: {confirm: 'Are you sure?'} %></p>
        </div>
    <% end %>
    </div>

app/views/comments/_form.html.erb
<h3>Add a comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>

<div class="form-group">
    <%= f.label:username %><br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
</div>
<div class="form-group">
    <%= f.label:body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
</div>
<p>
    <%= f.submit({:class => 'btn btn-secondary'}) %>
</p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>OroRailsBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">OroRailsBlog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= home_path %>">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= about_path %>">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= services_path %>">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= posts_path %>">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= contact_path %>">Contact</a>
          </li>
        </ul>
        <ul class="navbar-nav navbar-right">
          <li class="nav-item">
            <a class="nav-link" href="<%= new_post_path %>">Create Posts</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">

      <%= yield %>

    </main><!-- /.container -->
  </div>

</body>

</html>

app/views/pages/about.html.erb
<%= render 'pages/partials/content' %>

app/views/pages/contact.html.erb
<%= render 'pages/partials/content' %>

app/views/pages/index.html.erb
<%= render 'pages/partials/content' %>

app/views/pages/partials/_content.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/pages/services.html.erb
<%= render 'pages/partials/content' %>

<% for @service in @services%>
    <div class="card-body">
        <%= @service %>
    </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <div class="form-group">
        <%= f.label:title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </div>
    <div class="form-group">
        <%= f.label:body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </div>
    <p>
        <%= f.submit({:class => 'btn btn-secondary'}) %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Latest Blog Posts</h1>
<% @posts.each do |post| %>
    <div class="card-body">
        <h3><%= post.title %></h3>
        <hr>
        <p><%= post.body %></p>
        <%= link_to 'Read more', post_path(post), :class=> 'btn btn-secondary' %>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="car">
    <h1><%= @post.title %></h1>
    <hr>
    <p><%= @post.body %></p>
    <hr>
    <%= link_to 'Edit Post', edit_post_path(@post), :class => 'btn btn-secondary' %>
    <%= link_to 'Delete Post', post_path(@post), 
                                method: :delete,
                                data: {confirm: 'Are you sure?'},
                                :class => 'btn btn-danger delete-right' %>
</div>
<br>
<%= render 'comments/comments' %>
<br>
<%= render 'comments/form' %>